/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 *
 * Stand-in until the reference deployment lands: the frozen interface ABIs of Verdict, VerdictRouter and the
 * resolver at the zero address on Hedera testnet (296). The app treats a contract at the zero address as absent.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    Verdict: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          inputs: [],
          name: "AmountTooLarge",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "latest",
              type: "uint64",
            },
          ],
          name: "ExpiryTooFar",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "uint64",
              name: "earliest",
              type: "uint64",
            },
          ],
          name: "ExpiryTooSoon",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "FreshReadingExists",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "code",
              type: "int64",
            },
          ],
          name: "HssError",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "code",
              type: "int64",
            },
          ],
          name: "HtsError",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sent",
              type: "uint256",
            },
          ],
          name: "InsufficientValue",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidBounds",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "MarketNotExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "MarketNotOpen",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "MarketNotSettled",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "NoFreshReading",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "NoSuchMarket",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "NotAssociated",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToSweep",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "resolver",
              type: "address",
            },
          ],
          name: "ResolverNotAllowed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "earliest",
              type: "uint64",
            },
          ],
          name: "VoidTooEarly",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "resolver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "feedId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "enum IVerdict.Kind",
              name: "kind",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "lower",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "upper",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "yes",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "no",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "schedule",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "reserve",
              type: "uint256",
            },
          ],
          name: "MarketCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "Merged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "yesAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "noAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "paid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "Redeemed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "ResolveDeferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "payout",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "updatedAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "bySchedule",
              type: "bool",
            },
          ],
          name: "Resolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "resolver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "ResolverSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int64",
              name: "code",
              type: "int64",
            },
          ],
          name: "ScheduleFailed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "yesTo",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "noTo",
              type: "address",
            },
          ],
          name: "Split",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "SurplusSwept",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "by",
              type: "address",
            },
          ],
          name: "Voided",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_LEAD",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_LEAD",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "RESOLUTION_RESERVE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "VOID_DELAY",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "resolver",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "feedId",
              type: "bytes32",
            },
            {
              internalType: "enum IVerdict.Kind",
              name: "kind",
              type: "uint8",
            },
            {
              internalType: "int256",
              name: "lower",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "upper",
              type: "int256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
          ],
          name: "createMarket",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "creationCost",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "getMarket",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "creator",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "resolver",
                  type: "address",
                },
                {
                  internalType: "bytes32",
                  name: "feedId",
                  type: "bytes32",
                },
                {
                  internalType: "enum IVerdict.Kind",
                  name: "kind",
                  type: "uint8",
                },
                {
                  internalType: "enum IVerdict.Status",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint8",
                  name: "decimals",
                  type: "uint8",
                },
                {
                  internalType: "uint64",
                  name: "expiry",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "createdAt",
                  type: "uint64",
                },
                {
                  internalType: "int256",
                  name: "lower",
                  type: "int256",
                },
                {
                  internalType: "int256",
                  name: "upper",
                  type: "int256",
                },
                {
                  internalType: "address",
                  name: "yes",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "no",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "schedule",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "collateral",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "reserve",
                  type: "uint256",
                },
                {
                  internalType: "uint64",
                  name: "payout",
                  type: "uint64",
                },
                {
                  internalType: "int256",
                  name: "answer",
                  type: "int256",
                },
                {
                  internalType: "uint80",
                  name: "roundId",
                  type: "uint80",
                },
                {
                  internalType: "uint64",
                  name: "updatedAt",
                  type: "uint64",
                },
                {
                  internalType: "bool",
                  name: "settledBySchedule",
                  type: "bool",
                },
              ],
              internalType: "struct IVerdict.Market",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "marketCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "merge",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum IVerdict.Kind",
              name: "kind",
              type: "uint8",
            },
            {
              internalType: "int256",
              name: "lower",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "upper",
              type: "int256",
            },
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "payoutFor",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingReserves",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "yesAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "noAmount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "redeem",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "resolve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "resolveScheduled",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "resolver",
              type: "address",
            },
          ],
          name: "resolverAllowed",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "resolver",
              type: "address",
            },
            {
              internalType: "bool",
              name: "allowed",
              type: "bool",
            },
          ],
          name: "setResolver",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "yesTo",
              type: "address",
            },
            {
              internalType: "address",
              name: "noTo",
              type: "address",
            },
          ],
          name: "split",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "sweepSurplus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCollateral",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "voidMarket",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    VerdictRouter: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "Expired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "code",
              type: "int64",
            },
          ],
          name: "HtsError",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sent",
              type: "uint256",
            },
          ],
          name: "InsufficientValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "NoPool",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "NoSuchMarket",
          type: "error",
        },
        {
          inputs: [],
          name: "RouterNotEmpty",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "wanted",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "got",
              type: "uint256",
            },
          ],
          name: "Slippage",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "trader",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum IVerdictRouter.Trade",
              name: "trade",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountIn",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountOut",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refund",
              type: "uint256",
            },
          ],
          name: "Traded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minHbarBack",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "buyNo",
          outputs: [
            {
              internalType: "uint256",
              name: "noOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarBack",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minYesOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "buyYes",
          outputs: [
            {
              internalType: "uint256",
              name: "yesOut",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "impliedProbability",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "pairOf",
          outputs: [
            {
              internalType: "address",
              name: "pair",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarIn",
              type: "uint256",
            },
          ],
          name: "quoteBuyNo",
          outputs: [
            {
              internalType: "uint256",
              name: "noOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarBack",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarIn",
              type: "uint256",
            },
          ],
          name: "quoteBuyYes",
          outputs: [
            {
              internalType: "uint256",
              name: "yesOut",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "noIn",
              type: "uint256",
            },
          ],
          name: "quoteSellNo",
          outputs: [
            {
              internalType: "uint256",
              name: "hbarNeeded",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarOut",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "yesIn",
              type: "uint256",
            },
          ],
          name: "quoteSellYes",
          outputs: [
            {
              internalType: "uint256",
              name: "hbarOut",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "reserves",
          outputs: [
            {
              internalType: "uint256",
              name: "yesReserve",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "hbarReserve",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "noIn",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minHbarOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "sellNo",
          outputs: [
            {
              internalType: "uint256",
              name: "hbarOut",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "yesIn",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minHbarOut",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "sellYes",
          outputs: [
            {
              internalType: "uint256",
              name: "hbarOut",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    ChainlinkResolver: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "feedId",
              type: "bytes32",
            },
          ],
          name: "describe",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "feedId",
              type: "bytes32",
            },
          ],
          name: "feedDecimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "feedId",
              type: "bytes32",
            },
            {
              internalType: "uint64",
              name: "time",
              type: "uint64",
            },
          ],
          name: "readingAt",
          outputs: [
            {
              internalType: "bool",
              name: "ok",
              type: "bool",
            },
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
            {
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "uint64",
              name: "updatedAt",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
